language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-22
    - android-24
    - build-tools-24.0.2
    - extra-android-m2repository

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build
